export const SOURCE_TYPE_NULL = 'null'
export const SOURCE_TYPE_STATIC = 'static'
export const SOURCE_TYPE_REAL = 'real'
export const SOURCE_TYPE_ALARM = 'alarm'
export const SOURCE_TYPE_OVERVIEW = 'overview'
